// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Firebase project configuration
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDe17BUuijkQf0ViDacGLsaW9YVk2O_0A8',
    appId: '1:212421823653:web:c7923b19f4145b4a45914c',
    messagingSenderId: '212421823653',
    projectId: 'smartsplit-zanil',
    authDomain: 'smartsplit-zanil.firebaseapp.com',
    storageBucket: 'smartsplit-zanil.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDe17BUuijkQf0ViDacGLsaW9YVk2O_0A8',
    appId: '1:212421823653:android:c7923b19f4145b4a45914c',
    messagingSenderId: '212421823653',
    projectId: 'smartsplit-zanil',
    storageBucket: 'smartsplit-zanil.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDe17BUuijkQf0ViDacGLsaW9YVk2O_0A8',
    appId: '1:212421823653:ios:c7923b19f4145b4a45914c',
    messagingSenderId: '212421823653',
    projectId: 'smartsplit-zanil',
    storageBucket: 'smartsplit-zanil.appspot.com',
    iosBundleId: 'com.example.smartsplit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDe17BUuijkQf0ViDacGLsaW9YVk2O_0A8',
    appId: '1:212421823653:ios:c7923b19f4145b4a45914c',
    messagingSenderId: '212421823653',
    projectId: 'smartsplit-zanil',
    storageBucket: 'smartsplit-zanil.appspot.com',
    iosBundleId: 'com.example.smartsplit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDe17BUuijkQf0ViDacGLsaW9YVk2O_0A8',
    appId: '1:212421823653:web:c7923b19f4145b4a45914c',
    messagingSenderId: '212421823653',
    projectId: 'smartsplit-zanil',
    authDomain: 'smartsplit-zanil.firebaseapp.com',
    storageBucket: 'smartsplit-zanil.appspot.com',
  );
}
